USE WAREHOUSE WH_INMOBILIARIA;
USE DATABASE INMOBILIARIA_DW;

CREATE SCHEMA IF NOT EXISTS MANTENIMIENTO;

USE SCHEMA MANTENIMIENTO;

CREATE FILE FORMAT FF_MANTENIMIENTO_JSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;

CREATE STAGE STG_MANTENIMIENTO_SOLICITUD_S3
  URL = 's3://dataops-inmobiliaria-jeson-202608/inmobiliaria/mantenimiento/'
  FILE_FORMAT = FF_MANTENIMIENTO_JSON;

LIST @STG_MANTENIMIENTO_SOLICITUD_S3;

SELECT $1
FROM @STG_MANTENIMIENTO_SOLICITUD_S3
  (FILE_FORMAT => FF_MANTENIMIENTO_JSON)
LIMIT 5;

CREATE TABLE IF NOT EXISTS RAW_SOLICITUD (raw_data VARIANT)

COPY INTO RAW_SOLICITUD (raw_data)
FROM (
    SELECT $1 FROM @STG_MANTENIMIENTO_SOLICITUD_S3
)
FILE_FORMAT=(FORMAT_NAME=FF_MANTENIMIENTO_JSON)

