USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_INMOBILIARIA;
USE DATABASE INMOBILIARIA_DW;
USE SCHEMA MANTENIMIENTO;

CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER
    COMMENT = 'Opera el pipeline, necesita el dato crudo para depurar';
CREATE ROLE IF NOT EXISTS ROLE_DATA_ANALYST
    COMMENT = 'Analiza campañas, necesita contexto parcial, no el contacto completo';


GRANT USAGE ON WAREHOUSE WH_INMOBILIARIA TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_INMOBILIARIA TO ROLE ROLE_DATA_ANALYST;

GRANT USAGE ON DATABASE INMOBILIARIA_DW TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON DATABASE INMOBILIARIA_DW TO ROLE ROLE_DATA_ANALYST;

GRANT USAGE ON SCHEMA MANTENIMIENTO TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON SCHEMA MANTENIMIENTO TO ROLE ROLE_DATA_ANALYST;

GRANT SELECT ON TABLE STG_CONTACTOS_FLATTENED TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT ON TABLE STG_CONTACTOS_FLATTENED TO ROLE ROLE_DATA_ANALYST;

GRANT ROLE ROLE_DATA_ENGINEER    TO USER DPLETZKE;
GRANT ROLE ROLE_DATA_ANALYST     TO USER DPLETZKE;
 
CREATE OR REPLACE MASKING POLICY mask_contacto_telefono AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() = 'ROLE_DATA_ENGINEER' THEN val
    WHEN CURRENT_ROLE() = 'ROLE_DATA_ANALYST' THEN CONCAT(LEFT(val, 7), '-****')
    WHEN val IS NULL THEN NULL
    ELSE '***-***-****'
  END;
 
CREATE OR REPLACE MASKING POLICY mask_contacto_email AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() = 'ROLE_DATA_ENGINEER' THEN val
    WHEN CURRENT_ROLE() = 'ROLE_DATA_ANALYST' THEN CONCAT(
      LEFT(SPLIT_PART(val, '@', 1), 2),
      '***@',
      SPLIT_PART(val, '@', 2)
    )
    WHEN val IS NULL THEN NULL
    ELSE '***@***'
  END;
 
ALTER TABLE STG_CONTACTOS_FLATTENED
  MODIFY COLUMN contacto_telefono
  SET MASKING POLICY mask_contacto_telefono;
 
ALTER TABLE STG_CONTACTOS_FLATTENED
  MODIFY COLUMN contacto_email
  SET MASKING POLICY mask_contacto_email;
 
USE ROLE ROLE_DATA_ENGINEER;
USE WAREHOUSE WH_INMOBILIARIA;
 
SELECT
  event_id,
  contacto_nombre,
  contacto_telefono,
  contacto_email
FROM INMOBILIARIA_DW.MANTENIMIENTO.STG_CONTACTOS_FLATTENED
ORDER BY event_id, contacto_nombre;
 
USE ROLE ROLE_DATA_ANALYST;
USE WAREHOUSE WH_INMOBILIARIA;
 
SELECT
  event_id,
  contacto_nombre,
  contacto_telefono,
  contacto_email
FROM INMOBILIARIA_DW.MANTENIMIENTO.STG_CONTACTOS_FLATTENED
ORDER BY event_id, contacto_nombre;