USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_INMOBILIARIA
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS INMOBILIARIA_DW
    COMMENT='datawarehouse inmobiliaria';
CREATE SCHEMA IF NOT EXISTS INMOBILIARIA_DW.RAW
    COMMENT='Landing zone: datos de neon';

CREATE ROLE IF NOT EXISTS INMOBILIARIA_DATAOPS_LOADER
    COMMENT = 'Rol de servicio para el ELT de la Sesión 4. Sin privilegios de administración.';

GRANT USAGE ON WAREHOUSE WH_INMOBILIARIA TO ROLE INMOBILIARIA_DATAOPS_LOADER;
GRANT USAGE ON DATABASE INMOBILIARIA_DW TO ROLE INMOBILIARIA_DATAOPS_LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA INMOBILIARIA_DW.RAW TO ROLE INMOBILIARIA_DATAOPS_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA INMOBILIARIA_DW.RAW TO ROLE INMOBILIARIA_DATAOPS_LOADER;

GRANT ROLE INMOBILIARIA_DATAOPS_LOADER
    TO USER DPLETZKE;

USE WAREHOUSE WH_INMOBILIARIA;
USE DATABASE INMOBILIARIA_DW;
USE SCHEMA RAW;

----

SHOW WAREHOUSES LIKE 'WH_INMOBILIARIA';
SHOW SCHEMAS IN DATABASE INMOBILIARIA_DW;
SHOW GRANTS TO ROLE INMOBILIARIA_DATAOPS_LOADER;



