-- ===========================================================================
-- V202608121100__add_solicitud_mantenimiento.sql
-- ===========================================================================

CREATE TABLE solicitud_mantenimiento (
    id_solicitud     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inmueble      INTEGER NOT NULL REFERENCES inmueble (id_inmueble),
    id_empleado      INTEGER REFERENCES empleado (id_empleado),
    fecha_solicitud  DATE NOT NULL DEFAULT CURRENT_DATE,
    descripcion      TEXT NOT NULL,
    estado           TEXT NOT NULL DEFAULT 'abierta'
        CHECK (estado IN ('abierta','asignada','resuelta','cancelada')),
    CONSTRAINT chk_solicitud_asignada_tiene_empleado
        CHECK (estado <> 'asignada' OR id_empleado IS NOT NULL)
);

CREATE INDEX ix_solicitud_inmueble ON solicitud_mantenimiento (id_inmueble);
CREATE INDEX ix_solicitud_estado   ON solicitud_mantenimiento (estado);

INSERT INTO solicitud_mantenimiento (id_inmueble, id_empleado, fecha_solicitud, descripcion, estado)
SELECT im.id_inmueble,
       CASE WHEN im.id_inmueble % 4 = 0 THEN NULL
            ELSE 11 + (im.id_inmueble % 2) END,        -- empleados de mantenimiento (11, 12)
       (DATE '2026-01-15' + ((im.id_inmueble % 180) * INTERVAL '1 day'))::date,
       (ARRAY['Filtración en el baño principal',
              'Falla eléctrica en la cocina',
              'Cerradura de la puerta principal dañada',
              'Humedad en muro de la habitación',
              'Calentador no enciende'])[1 + (im.id_inmueble % 5)],
       CASE WHEN im.id_inmueble % 4 = 0 THEN 'abierta'
            WHEN im.id_inmueble % 4 = 1 THEN 'asignada'
            ELSE 'resuelta' END
FROM inmueble im
WHERE im.id_inmueble % 2 = 0;
