-- ===========================================================================
-- V202608121000__baseline_inmobiliaria.sql
-- ===========================================================================

CREATE TABLE rol_empleado (
    id_rol       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol   TEXT NOT NULL UNIQUE,
    descripcion  TEXT
);

CREATE TABLE empleado (
    id_empleado         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol              INTEGER NOT NULL REFERENCES rol_empleado (id_rol),
    id_supervisor       INTEGER REFERENCES empleado (id_empleado),
    nombre              TEXT NOT NULL,
    telefono            TEXT,
    fecha_contratacion  DATE NOT NULL DEFAULT CURRENT_DATE,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_empleado_no_se_supervisa
        CHECK (id_supervisor IS DISTINCT FROM id_empleado)
);

CREATE TABLE propietario (
    id_propietario       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               TEXT NOT NULL,
    documento_identidad  TEXT NOT NULL UNIQUE,
    telefono             TEXT,
    email                TEXT
);

CREATE TABLE cliente (
    id_cliente  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL,
    telefono    TEXT,
    email       TEXT NOT NULL UNIQUE
);

CREATE TABLE inmueble (
    id_inmueble           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propietario        INTEGER NOT NULL REFERENCES propietario (id_propietario),
    id_empleado_captador  INTEGER NOT NULL REFERENCES empleado (id_empleado),
    direccion             TEXT NOT NULL UNIQUE,
    tipo_inmueble         TEXT NOT NULL
        CHECK (tipo_inmueble IN ('apartamento','casa','local','oficina','bodega')),
    area_m2               NUMERIC(8,2)  NOT NULL CHECK (area_m2 > 0),
    habitaciones          SMALLINT      NOT NULL DEFAULT 0 CHECK (habitaciones >= 0),
    banos                 SMALLINT      NOT NULL DEFAULT 0 CHECK (banos >= 0),
    valor_arriendo        NUMERIC(14,2) CHECK (valor_arriendo > 0),
    valor_venta           NUMERIC(14,2) CHECK (valor_venta > 0),
    estado                TEXT NOT NULL DEFAULT 'disponible'
        CHECK (estado IN ('disponible','arrendado','vendido','retirado')),
    CONSTRAINT chk_inmueble_tiene_precio
        CHECK (valor_arriendo IS NOT NULL OR valor_venta IS NOT NULL)
);

CREATE TABLE contrato (
    id_contrato    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inmueble    INTEGER NOT NULL REFERENCES inmueble (id_inmueble),
    id_cliente     INTEGER NOT NULL REFERENCES cliente (id_cliente),
    id_empleado    INTEGER NOT NULL REFERENCES empleado (id_empleado),
    tipo_contrato  TEXT NOT NULL CHECK (tipo_contrato IN ('arriendo','venta')),
    fecha_inicio   DATE NOT NULL,
    fecha_fin      DATE,
    valor_total    NUMERIC(14,2) NOT NULL CHECK (valor_total > 0),
    estado         TEXT NOT NULL DEFAULT 'activo'
        CHECK (estado IN ('activo','terminado','anulado')),
    CONSTRAINT chk_contrato_vigencia
        CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio),
    CONSTRAINT chk_arriendo_tiene_fin
        CHECK (tipo_contrato <> 'arriendo' OR fecha_fin IS NOT NULL)
);

CREATE TABLE pago (
    id_pago      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato  INTEGER NOT NULL REFERENCES contrato (id_contrato),
    fecha_pago   DATE NOT NULL,
    monto        NUMERIC(14,2) NOT NULL CHECK (monto > 0),
    tipo_pago    TEXT NOT NULL
        CHECK (tipo_pago IN ('transferencia','efectivo','tarjeta','consignacion')),
    estado_pago  TEXT NOT NULL DEFAULT 'aplicado'
        CHECK (estado_pago IN ('aplicado','anulado','pendiente'))
);

CREATE INDEX ix_inmueble_propietario ON inmueble (id_propietario);
CREATE INDEX ix_contrato_inmueble    ON contrato (id_inmueble);
CREATE INDEX ix_contrato_cliente     ON contrato (id_cliente);
CREATE INDEX ix_pago_contrato        ON pago (id_contrato);

-- ---------------------------------------------------------------------------
-- Datos semilla.
-- ---------------------------------------------------------------------------

INSERT INTO rol_empleado (id_rol, nombre_rol, descripcion) VALUES
    (1, 'director',         'Dirige la operación; no reporta a nadie'),
    (2, 'coordinador',      'Coordina un equipo de asesores comerciales'),
    (3, 'asesor comercial', 'Capta inmuebles y gestiona contratos'),
    (4, 'mantenimiento',    'Atiende solicitudes sobre los inmuebles');

INSERT INTO empleado (id_empleado, id_rol, id_supervisor, nombre, telefono, fecha_contratacion, activo) VALUES
    ( 1, 1, NULL, 'Marcela Ortiz',    '3001110001', DATE '2019-02-11', TRUE),
    ( 2, 2,    1, 'Julián Restrepo',  '3001110002', DATE '2020-06-01', TRUE),
    ( 3, 2,    1, 'Paola Guerrero',   '3001110003', DATE '2021-01-18', TRUE),
    ( 4, 3,    2, 'Andrés Bermúdez',  '3001110004', DATE '2021-03-22', TRUE),
    ( 5, 3,    2, 'Laura Cárdenas',   '3001110005', DATE '2021-08-09', TRUE),
    ( 6, 3,    2, 'Diego Mahecha',    '3001110006', DATE '2022-02-14', TRUE),
    ( 7, 3,    3, 'Natalia Peña',     '3001110007', DATE '2022-05-30', TRUE),
    ( 8, 3,    3, 'Óscar Villamil',   '3001110008', DATE '2023-01-16', TRUE),
    ( 9, 3,    3, 'Camila Sanabria',  '3001110009', DATE '2023-07-03', TRUE),
    (10, 3,    3, 'Felipe Urrego',    '3001110010', DATE '2024-04-08', FALSE),
    (11, 4,    2, 'Wilson Ardila',    '3001110011', DATE '2022-09-19', TRUE),
    (12, 4,    3, 'Sandra Quintero',  '3001110012', DATE '2023-11-06', TRUE);

INSERT INTO propietario (id_propietario, nombre, documento_identidad, telefono, email)
SELECT i,
       (ARRAY['Ana','Carlos','Beatriz','Jorge','Luz','Hernán','Clara','Mauricio',
              'Rocío','Fernando'])[1 + (i % 10)]
         || ' ' ||
       (ARRAY['Gómez','Rincón','Salazar','Bohórquez','Muñoz','Lozano','Arévalo',
              'Cifuentes','Pardo','Tovar'])[1 + ((i * 3) % 10)],
       'CC' || LPAD((79000000 + i * 137)::text, 10, '0'),
       '31'  || LPAD((1000000 + i * 913)::text, 8, '0'),
       'propietario' || i || '@correo.co'
FROM generate_series(1, 40) AS i;

INSERT INTO cliente (id_cliente, nombre, telefono, email)
SELECT i,
       (ARRAY['Daniel','Mónica','Iván','Tatiana','Ricardo','Viviana','Sergio',
              'Adriana','Nicolás','Juliana'])[1 + (i % 10)]
         || ' ' ||
       (ARRAY['Cortés','Baquero','Zapata','Neira','Roldán','Espitia','Cuéllar',
              'Amaya','Bejarano','Piedrahíta'])[1 + ((i * 7) % 10)],
       '32' || LPAD((2000000 + i * 761)::text, 8, '0'),
       'cliente' || i || '@correo.co'
FROM generate_series(1, 60) AS i;

INSERT INTO inmueble (id_inmueble, id_propietario, id_empleado_captador, direccion,
                      tipo_inmueble, area_m2, habitaciones, banos,
                      valor_arriendo, valor_venta, estado)
SELECT i,
       1 + (i % 40),
       4 + (i % 7),                                    -- solo asesores (ids 4..10)
       'Calle ' || (20 + (i % 80)) || ' # ' || (5 + (i % 40))
                || '-' || (10 + (i % 60)) || ' Apto ' || (100 + i),
       (ARRAY['apartamento','casa','local','oficina','bodega'])[1 + (i % 5)],
       45 + (i % 120),
       CASE WHEN i % 5 IN (2, 4) THEN 0 ELSE 1 + (i % 4) END,
       1 + (i % 3),
       CASE WHEN i % 7 = 0 THEN NULL
            ELSE (1200000 + (i % 25) * 180000)::numeric(14,2) END,
       CASE WHEN i % 7 = 0 THEN (280000000 + (i % 30) * 21000000)::numeric(14,2)
            ELSE NULL END,
       CASE WHEN i % 7 = 0 THEN 'disponible' ELSE 'arrendado' END
FROM generate_series(1, 120) AS i;

INSERT INTO contrato (id_inmueble, id_cliente, id_empleado, tipo_contrato,
                      fecha_inicio, fecha_fin, valor_total, estado)
SELECT im.id_inmueble,
       1 + (im.id_inmueble % 60),
       4 + (im.id_inmueble % 7),
       'arriendo',
       (DATE '2025-01-01' + ((im.id_inmueble % 12) * INTERVAL '1 month'))::date,
       (DATE '2025-01-01' + ((im.id_inmueble % 12) * INTERVAL '1 month')
                          + INTERVAL '18 months')::date,
       im.valor_arriendo,
       'activo'
FROM inmueble im
WHERE im.valor_arriendo IS NOT NULL
ORDER BY im.id_inmueble;

INSERT INTO contrato (id_inmueble, id_cliente, id_empleado, tipo_contrato,
                      fecha_inicio, fecha_fin, valor_total, estado)
SELECT im.id_inmueble,
       1 + ((im.id_inmueble * 11) % 60),
       4 + ((im.id_inmueble * 5) % 7),
       'arriendo',
       DATE '2023-02-01',
       DATE '2024-08-01',
       (im.valor_arriendo * 0.88)::numeric(14,2),
       'terminado'
FROM inmueble im
WHERE im.valor_arriendo IS NOT NULL
  AND im.id_inmueble % 3 = 0
ORDER BY im.id_inmueble;

INSERT INTO pago (id_contrato, fecha_pago, monto, tipo_pago, estado_pago)
SELECT c.id_contrato,
       (m + INTERVAL '5 days')::date,
       c.valor_total,
       (ARRAY['transferencia','efectivo','tarjeta','consignacion'])[1 + (c.id_contrato % 4)],
       'aplicado'
FROM contrato c
CROSS JOIN LATERAL generate_series(
        c.fecha_inicio,
        LEAST(c.fecha_fin, DATE '2026-07-01'),
        INTERVAL '1 month') AS m
WHERE c.tipo_contrato = 'arriendo';

SELECT setval(pg_get_serial_sequence('rol_empleado','id_rol'),         (SELECT MAX(id_rol)         FROM rol_empleado));
SELECT setval(pg_get_serial_sequence('empleado','id_empleado'),        (SELECT MAX(id_empleado)    FROM empleado));
SELECT setval(pg_get_serial_sequence('propietario','id_propietario'),  (SELECT MAX(id_propietario) FROM propietario));
SELECT setval(pg_get_serial_sequence('cliente','id_cliente'),          (SELECT MAX(id_cliente)     FROM cliente));
SELECT setval(pg_get_serial_sequence('inmueble','id_inmueble'),        (SELECT MAX(id_inmueble)    FROM inmueble));
